# Generated by Django 4.0.5 on 2022-07-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Typing Text',
                'verbose_name_plural': 'Typing Text',
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='typing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.typing'),
        ),
    ]
