# Generated by Django 4.0.5 on 2022-07-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_typing_alter_hero_name_alter_hero_typing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='typing',
        ),
        migrations.AddField(
            model_name='hero',
            name='typing',
            field=models.ManyToManyField(to='core.typing'),
        ),
    ]
