# Generated by Django 4.0.5 on 2022-07-22 09:38

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_gallery_alter_blog_author_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='short_content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
