# Generated by Django 4.0.5 on 2022-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_gallery_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='%Y', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Year',
                'ordering': ('-created',),
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.AddField(
            model_name='gallery',
            name='year',
            field=models.CharField(blank=True, default='%Y', max_length=100, null=True),
        ),
    ]
