# Generated by Django 4.0.5 on 2022-07-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_year_remove_gallery_name_gallery_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='name',
        ),
    ]
