# Generated by Django 4.0.5 on 2022-07-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_year_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='name',
        ),
        migrations.AddField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, default='2022', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.ForeignKey(blank=True, default='2022', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
    ]
