# Generated by Django 4.0.5 on 2022-07-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_year_name_year_year_alter_gallery_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.ForeignKey(blank=True, default='%Y', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, default='%Y', max_length=100, null=True),
        ),
    ]
