# Generated by Django 4.0.5 on 2022-07-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_gallery_year_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.CharField(blank=True, default='%Y', max_length=100, null=True),
        ),
    ]
