# Generated by Django 4.0.5 on 2022-07-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_gallery_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
