# Generated by Django 4.0.5 on 2022-07-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_gallery_year_alter_year_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.year'),
        ),
    ]
