# Generated by Django 4.0.1 on 2022-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_gallery_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ('created',), 'verbose_name': 'Year', 'verbose_name_plural': 'Year'},
        ),
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='typing',
            field=models.ManyToManyField(to='core.Typing'),
        ),
    ]
